SRCDIR = srcdir
DESTDIR = destdir
PREFIX = prefix
PKGCTLBIN = $(SRCDIR)/src/pkgctl.py
FILES = $(SRCDIR)/FILES
VERSION = 1.1
PKGNAME = pkgctl
CATEGORY = base

all:
	echo "Run make install as root to install pkgctl ^_^"

install:
	install -m 755 $(PKGCTLBIN) $(DESTDIR)/$(PREFIX)/bin/pkgctl
	install -d -m 644 $(DESTDIR)/var/db/pkgctl/pkgctl
	install -d -m 644 $(DESTDIR)/$(PREFIX)/share/pkgctl/modules
	install -m 755 $(SRCDIR)/src/modules/fetch.py $(DESTDIR)/$(PREFIX)/share/pkgctl/modules/fetch.py
	install -m 755 $(SRCDIR)/src/modules/exitp.py $(DESTDIR)/$(PREFIX)/share/pkgctl/modules/exitp.py
	install -m 644  $(FILES) $(DESTDIR)/var/db/pkgctl/pkgctl/FILES
	echo $(VERSION) > $(DESTDIR)/var/db/pkgctl/pkgctl/VERSION
	echo $(PKGNAME) > $(DESTDIR)/var/db/pkgctl/pkgctl/PKGNAME
	echo $(CATEGORY) > $(DESTDIR)/var/db/pkgctl/pkgctl/CATEGORY
